id: P009391
initial_creation_type: ocr
source_metadata:
  id: bdr:W24168
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    c35f68b7782c4958ace2250f856c15e5:
      image_group_id: I1CZ980
      title: ''
      volume_number: 1
      total_pages: 104
